// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Security: No fallback credentials - fail fast in production
// In development, show helpful error but don't use hardcoded values
const isProduction = import.meta.env.PROD;
const isDevelopment = import.meta.env.DEV;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMessage = "Missing required Supabase environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)";
  
  if (isProduction) {
    // In production, throw immediately - no fallbacks
    throw new Error(`SECURITY ERROR: ${errorMessage}. The application cannot run without proper configuration.`);
  } else {
    // In development, show warning but still throw to prevent silent failures
    console.error(`❌ ${errorMessage}`);
    console.error("Please create a .env file with your Supabase credentials.");
    throw new Error(errorMessage);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use sessionStorage for better XSS protection (tokens cleared on tab close)
    storage: typeof window !== "undefined" ? window.sessionStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Enable PKCE flow detection
  },
});
