// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Fallbacks: these are *publishable* frontend values needed for the app to work in preview
// even when Vite env injection is missing.
const FALLBACK_SUPABASE_URL = "https://igjrpjvqwylxbblpwxrx.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnanJwanZxd3lseGJibHB3eHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY3MDMxMTAsImV4cCI6MjA4MjI3OTExMH0.MO4d9zm5SdG-pVrLPUYjB1lXN4vc5D8napA4ecGNazA";

const safeUrl = SUPABASE_URL || FALLBACK_SUPABASE_URL;
const safeKey = SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Supabase env missing at build-time; using fallback public config so the app can run in preview."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(safeUrl, safeKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
